### ISSUE TITLE
vim-taskwarrior should always set rc.defaulthegiht=0 override

### ISSUE THREAD

**Issue by tbabej** [blindFS/vim-taskwarrior#104] opened 2015-02-10 17:27 UTC
It does not make sense if tasks should be truncated in the report, for any reason.

**Comment by farseer90718** [comment] 2015-02-11 00:32
If you mean #103 , I think it is fixed now.

**Comment by tbabej** [comment] 2015-02-11 06:46
No, this is a separate problem. If you run:

    $ task next 

you will see that the report is truncated by the size of the terminal window, e.g.:

    <task1>
    <task2>
    ....
    <task15>
    254 tasks, truncated to 15 lines

This is what is happens when vim-taskwarrior uses the default ```:TW next``` report. I can tell because:

* setting rc.defaultheight=0 makes the problem go away.
* I dropped a small debugging diff into the taskwarrior itself:

     #include <text.h>
     #include <main.h>
     #include <CmdCustom.h>
     +#include <fstream>
 
     extern Context context;
 
    @@ -199,9 +201,15 @@ int CmdCustom::execute (std::string& output)
             out << ", " << format (STRING_CMD_CUSTOM_SHOWN, maxrows);
 
           if (maxlines && maxlines < (int)filtered.size ())
    +        {
             out << ", "
                  << format (STRING_CMD_CUSTOM_TRUNCATED, maxlines - table_header);
 
    +        using namespace std;
    +        ofstream logfile ("tasklog.log");
    +        logfile << format (STRING_CMD_CUSTOM_TRUNCATED, maxlines - table_header);
    +        logfile.close();
    +      }
           out << "\n";
         }
       }

The content of the ```tasklog.log``` after I run ```:TW``` in vim is:

    truncated to 17 lines

which is consistent with the fact that report shown by vim-taskwarrior indeed is only 17 lines high.

**Comment by Minoru** [comment] 2015-11-06 22:03
Can confirm that the problem is still present.

BTW, #117 seems to be a duplicate.

**Closed** 2015-11-07 02:12 UTC
